# config.yaml

# ----------------------- io params -----------------------
io:
  port: "COM4"
  baudrate: 921600
  is_wife: false
  model_path: "resource/model/model_torchscript.pt"
  model_param_path: "resource/model/parameters.json"

# ----------------------- filter params -----------------------
filter:
  update_freq: 20.0  # (Hz)
  sigma_na: 0.03162277660168379  # sqrt(1e-3), accel noise m/s^2
  sigma_ng: 0.01  # sqrt(1e-4), gyro noise rad/s
  ita_ba: 1e-4  # accel bias noise m/s^2/sqrt(s)
  ita_bg: 1e-6  # gyro bias noise rad/s/sqrt(s)
  init_attitude_sigma: 0.017453292519943295  # 1.0 / 180.0 * pi, rad
  init_yaw_sigma: 0.0017453292519943295  # 0.1 / 180.0 * pi, rad
  init_vel_sigma: 1.0  # m/s
  init_pos_sigma: 0.001  # m
  init_bg_sigma: 0.0001  # rad/s
  init_ba_sigma: 0.02  # m/s^2
  g_norm: 9.80
  meascov_scale: 10.0
  initialize_with_vio: false
  initialize_with_offline_calib: false
  calib: false
  mahalanobis_fail_scale: 0

# ----------------------- debug params -----------------------
debug:
  use_const_cov: false
  const_cov_val_x: 0.01  # 0.1^2
  const_cov_val_y: 0.01  # 0.1^2
  const_cov_val_z: 0.01  # 0.1^2
  add_sim_meas_noise: false
  sim_meas_cov_val: 0.0001  # 0.01^2
  sim_meas_cov_val_z: 0.0001  # 0.01^2
  force_cpu: false